name: Deploy Sphinx documentation to Pages

# Trigger the workflow on push events to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      # Deploy the documentation
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs/source
          requirements_path: ./requirements.txt
          publish: true

      # Publish the documentation to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}

